library(doBy); library(plotrix)
setwd("F:/Dropbox backup/HIE PhD/Data/Thesis analyses/ROS/Formal Analysis/Manuscript Analysis")
# rm(list=ls()); dev.off(); cat("\f") # ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

dat<-read.csv("ROS competition data all.csv")
dat<-summaryBy(CompEffect ~ Species * Phase * Experiment, FUN = c(mean, std.error), na.rm = T, dat)

tiff(file = "Figure_ROS CompEffects ~ Species + Phase + Experiment.tiff", height = 6.5, width = 10, res = 400, units = "in", compression = "zip+p")

xx<-c(-500,500); yy<-c(-500,500)
par(mfrow = c(3,3), mar = c(1,0,0,0), omi = c(1.05,1,0.5,0.5))

###############################################################
##############################################################################################################################
###############################################################

plot(xx ~ yy, xlim = c(0,4), ylim = c(-0.35,0.85), xaxt = "n", xlab = "", yaxt = "n", ylab = ""); abline(h = 0, lty = 1)


axis(1, at = seq(1,3,1), labels = F)
axis(2, at = seq(-1,1,0.25), cex.axis = 1.25, las = 2)
mtext(side = 3, expression(italic("F. arundinacea")), cex = 1.5)
df<-subset(dat, Experiment == "Short" & Species == "Fes" & Phase == "Resistance")
rect(0.75, 0, 1.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 1, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(1, 0.8, cex = 1.75, "a")
df<-subset(dat, Experiment == "Short" & Species == "Fes" & Phase == "Recovery")
rect(1.75, 0, 2.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 2, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(2, 0.8, cex = 1.75, "b")
df<-subset(dat, Experiment == "Short" & Species == "Fes" & Phase == "Control")
rect(2.75, 0, 3.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 3, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(3, 0.8, cex = 1.75, "b")
text(0.1, 0.75, "i)", cex = 2)

mtext(side = 2, "Increasing Competitive Effect", outer = T, cex = 1.15, padj = -5.25)
mtext(side = 2, "(i.e. Negative Effects of Competition on Aboveground Productivity)", outer = T, cex = 1.15, padj = -3.75)


plot(xx ~ yy, xlim = c(0,4), ylim = c(-0.35,0.85), xaxt = "n", xlab = "", yaxt = "n", ylab = ""); abline(h = 0, lty = 3)
axis(1, at = seq(1,3,1), labels = F)
# axis(2, at = seq(-1,1,0.25), cex.axis = 1.25, las = 2)
mtext(side = 3, expression(italic("P. aquatica")), cex = 1.5)
df<-subset(dat, Experiment == "Short" & Species == "Pha" & Phase == "Resistance")
rect(0.75, 0, 1.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 1, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(1, 0.8, cex = 1.75, "a")
df<-subset(dat, Experiment == "Short" & Species == "Pha" & Phase == "Recovery")
rect(1.75, 0, 2.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 2, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(2, 0.8, cex = 1.75, "c")
df<-subset(dat, Experiment == "Short" & Species == "Pha" & Phase == "Control")
rect(2.75, 0, 3.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 3, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(3, 0.8, cex = 1.75, "b")
text(0.1, 0.75, "ii)", cex = 2)


plot(xx ~ yy, xlim = c(0,4), ylim = c(-0.35,0.85), xaxt = "n", xlab = "", yaxt = "n", ylab = ""); abline(h = 0, lty = 3)
axis(1, at = seq(1,3,1), labels = F)
# axis(2, at = seq(-1,1,0.25), cex.axis = 1.25, las = 2)
mtext(side = 3, expression(italic("L. perenne")), cex = 1.5)
df<-subset(dat, Experiment == "Short" & Species == "Rye" & Phase == "Resistance")
rect(0.75, 0, 1.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 1, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(1, 0.8, cex = 1.75, "a")
df<-subset(dat, Experiment == "Short" & Species == "Rye" & Phase == "Recovery")
rect(1.75, 0, 2.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 2, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(2, 0.8, cex = 1.75, "c")
df<-subset(dat, Experiment == "Short" & Species == "Rye" & Phase == "Control")
rect(2.75, 0, 3.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 3, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(3, 0.8, cex = 1.75, "b")
text(0.1, 0.75, "iii)", cex = 2)

mtext(side = 4, "Short", cex = 1.5, padj = 1)

###############################################################
##############################################################################################################################
###############################################################

plot(xx ~ yy, xlim = c(0,4), ylim = c(-0.35,0.85), xaxt = "n", xlab = "", yaxt = "n", ylab = ""); abline(h = 0, lty = 3)
axis(1, at = seq(1,3,1), labels = F)
axis(2, at = seq(-1,1,0.25), cex.axis = 1.25, las = 2)
df<-subset(dat, Experiment == "Long" & Species == "Fes" & Phase == "Resistance")
rect(0.75, 0, 1.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 1, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(1, 0.8, cex = 1.75, "b")
df<-subset(dat, Experiment == "Long" & Species == "Fes" & Phase == "Recovery")
rect(1.75, 0, 2.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 2, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(2, 0.8, cex = 1.75, "a")
df<-subset(dat, Experiment == "Long" & Species == "Fes" & Phase == "Control")
rect(2.75, 0, 3.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 3, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(3, 0.8, cex = 1.75, "b")
text(0.1, 0.75, "iv)", cex = 2)


plot(xx ~ yy, xlim = c(0,4), ylim = c(-0.35,0.85), xaxt = "n", xlab = "", yaxt = "n", ylab = ""); abline(h = 0, lty = 3)
axis(1, at = seq(1,3,1), labels = F)
# axis(2, at = seq(-1,1,0.25), cex.axis = 1.25, las = 2)
df<-subset(dat, Experiment == "Long" & Species == "Pha" & Phase == "Resistance")
rect(0.75, 0, 1.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 1, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(1, 0.8, cex = 1.75, "a")
df<-subset(dat, Experiment == "Long" & Species == "Pha" & Phase == "Recovery")
rect(1.75, 0, 2.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 2, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(2, 0.8, cex = 1.75, "b")
df<-subset(dat, Experiment == "Long" & Species == "Pha" & Phase == "Control")
rect(2.75, 0, 3.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 3, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(3, 0.8, cex = 1.75, "b")
text(0.1, 0.75, "v)", cex = 2)


plot(xx ~ yy, xlim = c(0,4), ylim = c(-0.35,0.85), xaxt = "n", xlab = "", yaxt = "n", ylab = ""); abline(h = 0, lty = 3)
axis(1, at = seq(1,3,1), labels = F)
# axis(2, at = seq(-1,1,0.25), cex.axis = 1.25, las = 2)
df<-subset(dat, Experiment == "Long" & Species == "Rye" & Phase == "Resistance")
rect(0.75, 0, 1.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 1, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(1, 0.8, cex = 1.75, "b")
df<-subset(dat, Experiment == "Long" & Species == "Rye" & Phase == "Recovery")
rect(1.75, 0, 2.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 2, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(2, 0.8, cex = 1.75, "a")
df<-subset(dat, Experiment == "Long" & Species == "Rye" & Phase == "Control")
rect(2.75, 0, 3.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 3, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(3, 0.8, cex = 1.75, "b")
text(0.1, 0.75, "vi)", cex = 2)

mtext(side = 4, "Prolonged", cex = 1.5, padj = 1)

###############################################################
##############################################################################################################################
###############################################################

plot(xx ~ yy, xlim = c(0,4), ylim = c(-0.35,0.85), xaxt = "n", xlab = "", yaxt = "n", ylab = ""); abline(h = 0, lty = 3)
axis(1, at = seq(1,3,1), labels = c("Resistance","Recovery","Well-Watered"), cex.axis = 1.5, las = 2)
axis(2, at = seq(-1,1,0.25), cex.axis = 1.25, las = 2)
df<-subset(dat, Experiment == "Double" & Species == "Fes" & Phase == "Resistance")
rect(0.75, 0, 1.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 1, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(1, 0.8, cex = 1.75, "b")
df<-subset(dat, Experiment == "Double" & Species == "Fes" & Phase == "Recovery")
rect(1.75, 0, 2.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 2, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(2, 0.8, cex = 1.75, "a")
df<-subset(dat, Experiment == "Double" & Species == "Fes" & Phase == "Control")
rect(2.75, 0, 3.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 3, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(3, 0.8, cex = 1.75, "a")
text(0.1, 0.75, "vii)", cex = 2)


plot(xx ~ yy, xlim = c(0,4), ylim = c(-0.35,0.85), xaxt = "n", xlab = "", yaxt = "n", ylab = ""); abline(h = 0, lty = 3)
axis(1, at = seq(1,3,1), labels = c("Resistance","Recovery","Well-Watered"), cex.axis = 1.5, las = 2)
# axis(2, at = seq(-1,1,0.25), cex.axis = 1.25, las = 2)
df<-subset(dat, Experiment == "Double" & Species == "Pha" & Phase == "Resistance")
rect(0.75, 0, 1.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 1, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(1, 0.8, cex = 1.75, "b")
df<-subset(dat, Experiment == "Double" & Species == "Pha" & Phase == "Recovery")
rect(1.75, 0, 2.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 2, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(2, 0.8, cex = 1.75, "a")
df<-subset(dat, Experiment == "Double" & Species == "Pha" & Phase == "Control")
rect(2.75, 0, 3.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 3, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(3, 0.8, cex = 1.75, "a")
text(0.1, 0.75, "viii)", cex = 2)


plot(xx ~ yy, xlim = c(0,4), ylim = c(-0.35,0.85), xaxt = "n", xlab = "", yaxt = "n", ylab = ""); abline(h = 0, lty = 3)
axis(1, at = seq(1,3,1), labels = c("Resistance","Recovery","Well-Watered"), cex.axis = 1.5, las = 2)
# axis(2, at = seq(-1,1,0.25), cex.axis = 1.25, las = 2)
df<-subset(dat, Experiment == "Double" & Species == "Rye" & Phase == "Resistance")
rect(0.75, 0, 1.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 1, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(1, 0.8, cex = 1.75, "a")
df<-subset(dat, Experiment == "Double" & Species == "Rye" & Phase == "Recovery")
rect(1.75, 0, 2.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 2, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(2, 0.8, cex = 1.75, "b")
df<-subset(dat, Experiment == "Double" & Species == "Rye" & Phase == "Control")
rect(2.75, 0, 3.25, as.numeric(df$CompEffect.mean))
ablineclip(v = 3, y1 = as.numeric(df$CompEffect.mean-df$CompEffect.std.error), y2 = as.numeric(df$CompEffect.mean+df$CompEffect.std.error), lwd = 2)
text(3, 0.8, cex = 1.75, "c")
text(0.1, 0.75, "ix)", cex = 2)

mtext(side = 4, "Repeated", cex = 1.5, padj = 1)

dev.off()
